### ISSUE TITLE
Change Bank Transfer logo

### ISSUE THREAD

**Issue by LeoOosterloo** [pronamic/wp-pay-logos#5]
We now use following icon for Banktransfer:

https://github.com/pronamic/wp-pay-logos/blob/develop/src/methods/bank-transfer/method-bank-transfer-640x360.svg

For the casino sites we use the following Banktransfer icon:
![Bank Transfer (alt)-200x100](https://user-images.githubusercontent.com/610613/187949893-5e98cfe9-d0ae-4924-a44b-4ab323b3fcb4.svg)

I like this one more than we current one we use.

**Comment by LeoOosterloo** [comment]
> Do we know the source of this logo?

I don't have a source of newly suggested icon. It is more descriptive then the current icon. But I agree that it is not very user-friendly for non-English users.

**Comment by LeoOosterloo** [comment]
The current icon does not fully cover the load of a bank transfer. It also can mean 'send money' of 'tranfer coins/cash'.

A Google Search for Bank Transfer Icon gives the following results:
https://www.google.com/search?q=bank%2Btransfer%2Bicon&sca_esv=559082108&hl=en&tbm=isch&source=hp&biw=1706&bih=1241&ei=LrrkZIGRIsOWkwWrtLWwCw&iflsig=AD69kcEAAAAAZOTIPpKhqV5oy_hMnF_vH7Da94WZQhvV&ved=0ahUKEwiB4KPPsfCAAxVDy6QKHStaDbYQ4dUDCAc&uact=5&oq=bank%2Btransfer%2Bicon&gs_lp=EgNpbWciEmJhbmsrdHJhbnNmZXIraWNvbjIIEAAYBxgeGA8yBBAAGB4yBBAAGB4yBBAAGB4yBBAAGB4yBhAAGAgYHjIIEAAYCBgeGA8yCBAAGIoFGIYDMggQABiKBRiGAzIIEAAYigUYhgNI8iVQlgFY3yNwAXgAkAEAmAE8oAF1qgEBMrgBA8gBAPgBAvgBAYoCC2d3cy13aXotaW1nqAIA&sclient=img

It shows two main versions:
1. An icon with a bank building and an arrow
2. Text icon like above.

Maybe we should do some more research? If we want to use the icon in multiple languages we should not use a text icon.
Then a bank building with an arrow covers the load better then our current logo? What do you think @remcotolsma?

**Comment by remcotolsma** [comment]
Some sources of the new suggested version from @LeoOosterloo:

- https://www.flaticon.com/free-icon/bank-transfer_349229
- https://www.svgrepo.com/svg/266069/bank-transfer
- https://favpng.com/png_view/bank-wire-transfer-electronic-funds-transfer-bank-payment-png/vzH3htca
- https://www.shareicon.net/financial-cash-finance-business-pay-credit-card-donation-checkout-payment-buy-banktransfer-100658
- https://www.iconfinder.com/icons/243827/bank_transfer_card_checkout_money_transfer_online_shopping_payment_method_service_icon
- https://creazilla.com/nodes/3249083-bank-transfer-icon
- https://github.com/AlexanderPoellmann/PaymentFont

If we search for 'bank transfer icon' or 'bank wire icon' we see all kinds of variations.

<img width="1819" alt="Scherm­afbeelding 2023-08-22 om 15 45 38" src="https://github.com/pronamic/wp-pay-logos/assets/869674/c29b6391-314e-411e-bf0d-d63214c48b36">

I think the traditional banks (and buildings 🏦) will increasingly disappear, many large webshops in the Netherlands no longer offer the 'bank transfer' payment method?

In any case, the icon with the bank transfer method will always be less recognizable, because it is unbranded and there is no uniform icon and method for it.

Do we want to use a traditional bank building in the logo or a more general icon for transferring money?
https://fontawesome.com/icons/money-bill-transfer?f=classic&s=solid

I believe Mollie uses the SEPA icon for the bank transfer method, probably because their bank transfers are also limited to SEPA (Single Euro Payments Area)?

https://github.com/pronamic/wp-pay-logos/blob/dbf9c7de666993d66129c4a6674745d40c7f67fe/dist/other/sepa/sepa-640x360.svg

Many bank transfers also go through an IBAN, possibly the IBAN logo could also be a choice:

![iban2](https://github.com/pronamic/wp-pay-logos/assets/869674/9b2e3907-cb4b-403f-8cdf-9d669aba29b2)

<img width="1819" alt="Scherm­afbeelding 2023-08-22 om 16 03 56" src="https://github.com/pronamic/wp-pay-logos/assets/869674/610810d3-212c-4139-a8c3-591559e7e243">

**Comment by LeoOosterloo** [comment]
> Many bank transfers also go through an IBAN, possibly the IBAN logo could also be a choice

IBAN logo is limited to Europe. We exclude the rest of the world with that.

- Mollie does indeed use the SEPA icon for bank transfers: https://www.mollie.com/nl/payments/bank-transfer
- Stripe uses a bank building for bank transfers: https://stripe.com/nl/payments/europe-bank-transfers
- Adyen uses a bank building for 'online banking: https://www.adyen.com/payment-methods?paymentMethodTypes=Online%20banking (not exactly the same)
- Buckaroo uses 'SEPA Credit Transfer' icon: https://www.buckaroo.nl/oplossingen/betaalmethoden/sepa-credit-transfer
- MultiSafepay uses a text based icon 'BankTransfer': https://www.multisafepay.com/nl_nl/oplossingen/betaalmethoden/bank-transfer#learnmore
- Pay.nl uses the SEPA Credit Transfer icon: https://www.pay.nl/betaalmethoden/bankbetalingen/overboeking

Using a SEPA icon is also limited to Europe with 34 countries.
A bank transfer is a pretty old (fashioned) payment option. In that case we can use a bank(building) as icon
or we can go for a more modern approach and use the SEPA icon (with European limitations).

**Comment by rvdsteege** [comment]
> IBAN logo is limited to Europe. We exclude the rest of the world with that.

I don't like using an IBAN logo for bank transfers (prefer something without SEPA, e.g. the bank building), but IBAN is not EU only according to Wikipedia:

> Initially developed to facilitate payments within the European Union, it has been implemented by most European countries and numerous countries in other parts of the world, mainly in the Middle East and the Caribbean. As of July 2023, 86 countries were using the IBAN numbering system.

ℹ️ https://en.wikipedia.org/wiki/International_Bank_Account_Number

**Comment by remcotolsma** [comment]
A traditional bank building icon such as Adyen uses is the most common and recognizable?

<img width="1819" alt="Scherm­afbeelding 2023-08-23 om 11 59 54" src="https://github.com/pronamic/wp-pay-logos/assets/869674/7957ce15-b840-410a-b318-4a2f30402f30">

We can always include the IBAN logo in the logos library, users who prefer to use this icon can use it. Just like the SEPA icon which is already part of this library and can be used if desired.

**Comment by LeoOosterloo** [comment]
I made two versions with a traditional bank-building based on: 
https://fontawesome.com/icons/building-columns?f=classic&s=solid

Just a bank building
![method-bank-transfer-640x360](https://github.com/pronamic/wp-pay-logos/assets/610613/6831b426-79ba-4232-afd8-c5f0fbde36c6)
[bank-transfer.zip](https://github.com/pronamic/wp-pay-logos/files/12486426/bank-transfer.zip)

A bank building with arrows
![method-bank-transfer-arrows-640x360](https://github.com/pronamic/wp-pay-logos/assets/610613/131cb16a-dba8-465a-9cd2-1dacb4ae3d49)
[bank-transfer-arrows.zip](https://github.com/pronamic/wp-pay-logos/files/12486425/bank-transfer-arrows.zip)

**Comment by remcotolsma** [comment]
I have added the IBAN logo:
https://github.com/pronamic/wp-pay-logos/blob/main/dist/other/iban/iban-640x360.svg

And the bank icon from https://fontawesome.com/icons/building-columns?f=classic&s=solid:
https://github.com/pronamic/wp-pay-logos/blob/fd0312d3b48fc3ea82a24f293eede746fc30e6ac/dist/methods/bank-transfer/method-bank-transfer-640x360.svg
